### ISSUE TITLE
limiting canary_filter_regex to one instance

### ISSUE THREAD

**Issue by hrlokesh-sky** [dseeley/clusterverse#26]
Morning. Hope you are doing good. just got a question on clusterverse where we are redeploying hosts to use latest ami's. while we are selecting filter as '
-e canary=filter -e redeploy_scheme=_scheme_rmvm_keepdisk_rollback -e canary_filter_regex='kfk-sandbox-broker-a1
' its selecting multiple instances like
kfk-sandbox-broker-a10, kfk-sandbox-broker-a11,kfk-sandbox-broker-a12...etc
but we have to limit it to one instance at a time as we don't want other instances to go down at same time. can you please suggest how to limit it to one instance.   Seems the regex is identifying the hosts matches to a1().

**Comment by dseeley** [comment]
Have you tried `-e canary_filter_regex='^kfk-sandbox-broker-a1$'`?

**Comment by dseeley** [comment]
Although, with that redeploy scheme, using `canary=start` will shut down and replace the first host only (usually `a0`).  If you subsequently do `canary=finish`, it will shut down each remaining instance (and build its replacement), one-by-one.

**Comment by hrlokesh-sky** [comment]
@dseeley, I tried this pattern 

`-e canary_filter_regex='^kfk-sandbox-broker-a1$'`

 it didn't work as its not selecting any host

"msg": "Canary redeploy (filter) selected; deleting and redeploying []"

**Comment by dseeley** [comment]
> @dseeley, I tried this pattern
> 
> `-e canary_filter_regex='^kfk-sandbox-broker-a1$'`
> 
> it didn't work as its not selecting any host
> 
> "msg": "Canary redeploy (filter) selected; deleting and redeploying []"
> 
> I am using this argument --> -e canary=filter -e redeploy_scheme=_scheme_rmvm_keepdisk_rollback --skip-tags=tenable-agent -e canary_filter_regex='^kfk-core-broker-a0-.*$'

Right - the regex is wrong - should be ^opensearch-dev-data-a0-.*

**Comment by hrlokesh-sky** [comment]
> > @dseeley, I tried this pattern
> > `-e canary_filter_regex='^kfk-sandbox-broker-a1$'`
> > it didn't work as its not selecting any host
> > "msg": "Canary redeploy (filter) selected; deleting and redeploying []"
> > I am using this argument --> -e canary=filter -e redeploy_scheme=_scheme_rmvm_keepdisk_rollback --skip-tags=tenable-agent -e canary_filter_regex='^kfk-core-broker-a0$'
> 
> Right - the regex is wrong - should be `^kfk-core-broker-a0-.*$`

I used this regex but it didn't stop the broker-a0 and create the new one :( .

TASK [/var/slave_workspace/workspace/kafka-cluster-infra-redeploy/provisioning/aws/confluent-infra/roles/clusterverse/redeploy/_scheme_rmvm_keepdisk_rollback : debug] ***
Friday 08 December 2023  12:30:33 +0000 (0:00:00.264)       0:03:19.908 ******* 
ok: [localhost] => {
    "msg": "by_hosttype_by_host | Attempting to redeploy kfk-core-broker-a0-1614876685"
}

TASK [by_hosttype_by_host | run predeleterole role] ****************************
Friday 08 December 2023  12:30:33 +0000 (0:00:00.185)       0:03:20.093 ******* 
skipping: [localhost]

TASK [by_hosttype_by_host | Power off old VM] **********************************
Friday 08 December 2023  12:30:33 +0000 (0:00:00.129)       0:03:20.223 ******* 

TASK [clusterverse/redeploy/__common : powerchange_vms/aws | hosts_to_powerchange (to stop)] ***
Friday 08 December 2023  12:30:34 +0000 (0:00:00.338)       0:03:20.561 ******* 
ok: [localhost] => {
    "msg": []
}

**Comment by dseeley** [comment]
> I'll have a look.

This would be quite a nuisance to fix.  Without understanding why the normal `canary=start`, `canary=finish` (and/or `myhosttypes=`) is not adequate, I'm reluctant to invest a lot of time in it.  To reiterate - this redeploy scheme redeploys the hosts one-by-one - only one machine goes down at a time.

**Comment by hrlokesh-sky** [comment]
> OK - it looks like there is an issue here with handling of `canary=filter` (the `lifecycle_state` is not being changed). I didn't write that bit btw!
> 
> I'll have a look.

yeah, you are right that tag is the key bit, i have changed it to redployfail and it is working now

**Comment by dseeley** [comment]
> yeah, you are right that tag is the key bit, i have changed it to redpeloyfail and it is working now. but our requirement is to limit it to one instance when we have instaces numbered a0 to a12, it works for a0 but when we select a1 it loops all instnaces starting with a1 ( in this case it is a10,a11,a12). So I will try with ^kfk-core-broker-a1-.*$ . hope this works :).

That regex should fix that problem, but I'm still curious why you want to run the playbook manually for each host individually?  It does that automatically, by itself...

**Comment by hrlokesh-sky** [comment]
> > yeah, you are right that tag is the key bit, i have changed it to redpeloyfail and it is working now. but our requirement is to limit it to one instance when we have instaces numbered a0 to a12, it works for a0 but when we select a1 it loops all instnaces starting with a1 ( in this case it is a10,a11,a12). So I will try with ^kfk-core-broker-a1-.*$ . hope this works :).
> 
> That regex should fix that problem, but I'm still curious why you want to run the playbook manually for each host individually? It does that automatically, by itself...

Morning Dougal, its because we have to install and configure kafka broker on the host before it moves to the next one.

**Comment by dseeley** [comment]
> > That regex should fix that problem, but I'm still curious why you want to run the playbook manually for each host individually? It does that automatically, by itself...
> 
> Morning Dougal, its because we have to install and configure kafka broker on the host before it moves to the next one.

You're not using your Ansible playbook to do this?
